---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: websites
  labels:
    app.kubernetes.io/name: team-organiser
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: team-organiser
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: team-organiser
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: cbeneke/team-organiser-backend:{{ $.Values.image.tag }}
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: backend
