---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: websites
  labels:
    app.kubernetes.io/name: team-organiser
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: team-organiser
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: team-organiser
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: cbeneke/team-organiser-backend:{{ $.Values.image.tag }}
        environment:
        - key: DATABASE_URL
          value: /data/backend.db
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data
      #  - name: config
      #    mountPath: /app/config
      #volumes:
      #- name: config
      #  configMap:
      volumeClaimTemplates:
      - metadata:
          name: data
        spec:
          resources:
            requests:
              storage: 10Gi
