---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: team-organiser
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: team-organiser
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: team-organiser
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: frontend
        image: cbeneke/team-organiser-web:{{ $.Values.image.tag }}
        ports:
        - name: http
          containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: frontend
