apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: team-organiser
    app.kubernetes.io/component: frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $.Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              name: http
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ $.Values.hostname }}
    secretName: {{ $.Values.hostname | replace "." "-" }}-tls
