name: Build Image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Generate short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cbeneke
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: cbeneke/team-organiser-backend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: cbeneke/team-organiser-backend:${{ steps.vars.outputs.sha_short }}

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          tags: cbeneke/team-organiser-web:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          tags: cbeneke/team-organiser-web:${{ steps.vars.outputs.sha_short }}