name: Build
on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.tag_name }}
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Build tag name
      id: tag
      shell: bash
      run: |
        sha_short=$(git rev-parse --short "$GITHUB_SHA")
        branch=$(echo ${GITHUB_REF#refs/heads/})
        if [[ "${branch}" == "main" ]]; then
          tag_name="${sha_short}"
        else
          tag_name="${branch}.${sha_short}"
        fi
        echo "tag_name=${tag_name}" >> "$GITHUB_OUTPUT"
  backend:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-backend:${{ needs.prepare.outputs.tag_name }}
  web:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push web frontend
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-web:${{ needs.prepare.outputs.tag_name }}
