name: Build Dev Image

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cbeneke
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: cbeneke/team-organiser-backend:development

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./app
          tags: cbeneke/team-organiser-web:development