name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run pytest
      run: |
        cd backend/
        pytest tests

  black:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black --check --diff backend/src backend/alembic/versions backend/tests
  backend:
    runs-on: ubuntu-latest
    needs:
      - pytest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./backend/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-backend:dev
  web:
    runs-on: ubuntu-latest
    needs:
      - black
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push web frontend
      uses: docker/build-push-action@v6
      with:
        context: ./app/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-web:dev
