name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run pytest
      run: |
        cd backend/
        pytest tests

  black:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black --check --diff backend/src backend/alembic/versions backend/tests

  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag_name }}
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Build tag name
      id: tag
      shell: bash
      run: |
        echo "tag_name=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"
  backend:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - pytest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-backend:${{ needs.prepare.outputs.tag_name }}
  web:
    runs-on: ubuntu-latest
    needs:
      - prepare
      - black
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push web frontend
      uses: docker/build-push-action@v5
      with:
        context: ./app/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-web:${{ needs.prepare.outputs.tag_name }}
