name: CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v6
      with:
        context: ./backend/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-backend:${{ github.ref_name }}

  web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cbeneke
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push web frontend
      uses: docker/build-push-action@v6
      with:
        context: ./app/
        push: true
        platforms: linux/amd64,linux/arm64
        tags: cbeneke/team-organiser-web:${{ github.ref_name }}
